import { exec } from 'child_process';
import { promisify } from 'util';
import { Octokit } from '@octokit/rest';
import { LogEmitter } from './logs';

const execAsync = promisify(exec);

let octokitClient: Octokit | null = null;

function getOctokitClient(): Octokit {
  if (!octokitClient) {
    octokitClient = new Octokit({
      auth: process.env.GITHUB_TOKEN
    });
  }
  return octokitClient;
}

export async function pushBranchAndOpenPR(
  repoDir: string,
  branchName: string,
  prompt: string,
  githubRepo: string,
  baseBranch: string,
  log: LogEmitter
): Promise<string> {
  // Parse owner/repo
  const [owner, repo] = githubRepo.split('/');
  if (!owner || !repo) {
    throw new Error(`Invalid github_repo format: ${githubRepo}. Expected "owner/repo"`);
  }

  // Push branch
  log.emit(`Pushing branch ${branchName} to remote...`);
  try {
    await execAsync(`git -C "${repoDir}" push origin "${branchName}"`, {
      env: { ...process.env, GIT_TERMINAL_PROMPT: '0' }
    });
  } catch (error: any) {
    throw new Error(`Failed to push branch: ${error.stderr || error.message}`);
  }

  // Create PR
  log.emit('Creating pull request...');
  const title = `VIBE: ${prompt.slice(0, 60)}${prompt.length > 60 ? '...' : ''}`;
  const body = `## VIBE-Generated Changes

**Prompt:** ${prompt}

### Changes
This PR was automatically generated by VIBE based on the prompt above.

### Preflight Results
All preflight checks passed:
- ✓ Install
- ✓ Typecheck
- ✓ Lint
- ✓ Tests

---
*This PR was automatically generated by VIBE*`;

  const octokit = getOctokitClient();
  try {
    const response = await octokit.pulls.create({
      owner,
      repo,
      title,
      body,
      head: branchName,
      base: baseBranch
    });

    return response.data.html_url;
  } catch (error: any) {
    throw new Error(`Failed to create PR: ${error.message}`);
  }
}
