import { Octokit } from '@octokit/rest';

const octokit = new Octokit({
  auth: process.env.GITHUB_TOKEN
});

export interface PrCreationParams {
  repoUrl: string;
  sourceBranch: string;
  targetBranch: string;
  prompt: string;
  taskId: string;
  iterationCount: number;
}

export interface PrCreationResult {
  success: boolean;
  prUrl?: string;
  error?: string;
}

// Parse GitHub repo URL to extract owner and repo
function parseRepoUrl(repoUrl: string): { owner: string; repo: string } | null {
  // Support formats: https://github.com/owner/repo or git@github.com:owner/repo.git
  const httpsMatch = repoUrl.match(/github\.com\/([^\/]+)\/([^\/\.]+)/);
  const sshMatch = repoUrl.match(/github\.com:([^\/]+)\/([^\.]+)/);
  
  const match = httpsMatch || sshMatch;
  if (!match) {
    return null;
  }

  return {
    owner: match[1],
    repo: match[2]
  };
}

// Create GitHub PR
export async function createGitHubPr(params: PrCreationParams): Promise<PrCreationResult> {
  try {
    const repoInfo = parseRepoUrl(params.repoUrl);
    if (!repoInfo) {
      return {
        success: false,
        error: 'Invalid GitHub repository URL'
      };
    }

    // Generate PR title (first 60 chars of prompt)
    const title = `VIBE: ${params.prompt.slice(0, 60)}${params.prompt.length > 60 ? '...' : ''}`;

    // Generate PR body with metadata
    const body = `## VIBE-Generated Changes

**Task ID:** ${params.taskId}
**Iterations:** ${params.iterationCount}
**Source Branch:** ${params.sourceBranch}
**Target Branch:** ${params.targetBranch}

### Original Prompt
${params.prompt}

### Preflight Results
All preflight checks passed:
- ✓ Lint
- ✓ Typecheck
- ✓ Tests
- ✓ Smoke tests

---
*This PR was automatically generated by VIBE*`;

    // Create the pull request
    const response = await octokit.pulls.create({
      owner: repoInfo.owner,
      repo: repoInfo.repo,
      title,
      body,
      head: params.targetBranch,
      base: params.sourceBranch
    });

    return {
      success: true,
      prUrl: response.data.html_url
    };

  } catch (error: any) {
    return {
      success: false,
      error: error.message || 'Failed to create PR'
    };
  }
}
