import { execAsync } from './utils';
import { LogEmitter } from './logs';

export async function pushBranchAndOpenPR(
  repoDir: string,
  branchName: string,
  prompt: string,
  githubRepo: string, // "owner/repo"
  log: LogEmitter
): Promise<string> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('GITHUB_TOKEN not set');

  // Set remote with auth token
  const remoteUrl = `https://x-access-token:${token}@github.com/${githubRepo}.git`;
  await execAsync(`git -C "${repoDir}" remote set-url origin "${remoteUrl}"`);

  // Push branch
  await execAsync(`git -C "${repoDir}" push origin "${branchName}" --force`);
  log.emit(`Branch pushed: ${branchName}`);

  // Open PR via GitHub API
  const [owner, repo] = githubRepo.split('/');
  const prTitle = `[VIBE] ${prompt.slice(0, 72)}`;
  const prBody = `Auto-generated by VIBE\n\n**Prompt:** ${prompt}`;

  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      'Content-Type': 'application/json',
      Accept: 'application/vnd.github+json',
    },
    body: JSON.stringify({
      title: prTitle,
      body: prBody,
      head: branchName,
      base: 'main',
    }),
  });

  if (!res.ok) {
    const detail = await res.text();
    throw new Error(`GitHub PR creation failed: ${res.status} ${detail}`);
  }

  const pr = (await res.json()) as { html_url: string };
  return pr.html_url;
}
